name: dovalclubWeb
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # webview_flutter: ^1.0.7
  splashscreen: ^1.3.5
  flutter_launcher_icons: ^0.8.1
  shared_preferences: ^0.5.12+4
  video_player: ^1.0.1
  flutter_inappwebview: ^4.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - images/